CREATE TABLE [dbo].[MM_FavoriteSpot]
(
	[IdSpot] UNIQUEIDENTIFIER NOT NULL, 
	[IdUser] UNIQUEIDENTIFIER NOT NULL,
	[IsFavorite] BIT NOT NULL DEFAULT 1,
	[CreatedAt] DATETIME2 NOT NULL DEFAULT GETDATE(),
	[UpdatedAt] DATETIME2 NULL,
	CONSTRAINT [PK_FavoriteSpot] PRIMARY KEY ([IdSpot], [IdUser]),
	CONSTRAINT [FK_FavoriteSpot_Spot] FOREIGN KEY ([IdSpot]) REFERENCES [Spot]([IdSpot]), 
	CONSTRAINT [FK_FavoriteSpot_User] FOREIGN KEY ([IdUser]) REFERENCES [User]([IdUser]) 
)
