CREATE TABLE [dbo].[Rating]
(
	[IdRating] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	[Score] INT NOT NULL,
	[IsDeleted] BIT NOT NULL DEFAULT 0,
	[CreatedAt] DATETIME2 NOT NULL DEFAULT GETDATE(),
	[UpdatedAt] DATETIME2 NULL,
	[DeletedAt] DATETIME2 NULL,
	[CreatedBy] UNIQUEIDENTIFIER NOT NULL,
	[UpdatedBy] UNIQUEIDENTIFIER NULL,
	[DeletedBy] UNIQUEIDENTIFIER NULL,
	CONSTRAINT [PK_Rating] PRIMARY KEY ([IdRating]),
	CONSTRAINT [CK_Rating_Score] CHECK ([Score] BETWEEN 0 AND 10),
	CONSTRAINT [FK_Rating_CreateBy] FOREIGN KEY ([CreatedBy]) REFERENCES [User]([IdUser]),
	CONSTRAINT [FK_Rating_UpdatedBy] FOREIGN KEY ([UpdatedBy]) REFERENCES [User]([IdUser]),
	CONSTRAINT [FK_Rating_DeletedBy] FOREIGN KEY ([DeletedBy]) REFERENCES [User]([IdUser])
)
