CREATE TABLE [dbo].[User]
(
	[IdUser] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	[FirstName] NVARCHAR(50) NULL, 
	[LastName] NVARCHAR(50) NULL, 
	[NickName] NVARCHAR(50) NOT NULL CONSTRAINT UK_USER_NickName UNIQUE, 
	[Login] NVARCHAR(100) NOT NULL CONSTRAINT UK_USER_Login UNIQUE, 
	[Email] NVARCHAR(500) NOT NULL CONSTRAINT UK_USER_Email UNIQUE, 
	[Password] NVARCHAR(200) NOT NULL, 
	[Salt] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(), 
	[Avatar] NVARCHAR(200) NOT NULL DEFAULT 'Not Implemented', 
	[CreatedAt] DATETIME2 NOT NULL DEFAULT GETDATE(), 
	[UpdatedAt] DATETIME2 NULL, 
    CONSTRAINT [PK_User] PRIMARY KEY ([IdUser])
)
